apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-worker
  template:
    metadata:
      labels:
        app: payment-worker
    spec:
      containers:
      - name: payment-worker
        image: SEU_USUARIO_DOCKERHUB/payment-worker:latest # Substitua aqui
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"